- hosts: public
  tasks:
          - name: "Create user public"
            user:
                    name: public
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/public

- hosts: fe
  tasks:
          - name: "Create user frontend"
            user:
                    name: fe
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/

- hosts: be
  tasks:
          - name: "Create user backend"
            user:
                    name: be
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/be

- hosts: db
  tasks:
          - name: "Create user database"
            user:
                    name: db
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/db

- hosts: jk
  tasks:
          - name: "Create user jenkins"
            user:
                    name: jk
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/jk

- hosts: pm
  tasks:
          - name: "Create user prometheus"
            user:
                    name: ps
                    password: "$hNI82fq4WA1/DsKaIDANTOJ0lqJmGQ5dg8viFF.qzRL1m6neluUtol65yTo1Re2trApawwXpyDiFAIZHNwMOM/"
                    groups: sudo
                    state: present
                    shell: /bin/hash
                    system: no
                    createhome: yes
                    home: /home/pm

# Change PasswordAuthentication and rload sshd
- hosts: all
  tasks:
          - name: change PasswordAuth
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: 'PasswordAuthentication no'
                    line: PasswordAuthentication yes

          - name: reload sshd
            systemd:
                    name: sshd
                    state: reloaded
