- hosts: pm
  tasks:
    - name: mkdir docker
      file:
        path: /home/ubuntu/prometheus
        state: directory

    - name: copy prometheus conf
      copy:
        src: docker_images/prometheus.yml
        dest: /home/ubuntu/prometheus/prometheus.yml

    - name: run prometheus
      command: docker run --name prometheus -p 9090:9090 -d -v /home/ubuntu/prometheus:/etc/prometheus prom/prometheus

    - name: run grafana
      command: docker run --name grafana -d -p 3000:3000 grafana/grafana