- hosts: fe
  tasks:
          - name: run housy-fe
            command: docker run --name frontend -it -p 3000:3000 eidoscore/frontend_housy

- hosts: be
  tasks:
          - name: run housy-be
            command: docker run --name backend -p 5000:5000 -d eidoscore/backend_housy

- hosts: jk
  tasks:
          - name: run jenkins
            command: docker run --name jenkins -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/usr/app jenkins/jenkins:lts

